// Code generated by swaggo/swag. DO NOT EDIT.

package docs_v3

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {},
    "info": {"contact":{"email":"contato@jsfelipearaujo.com","name":"Jose Felipe"},"description":"{{escape .Description}}","license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0.html"},"title":"{{.Title}}","version":"{{.Version}}"},
    "externalDocs": {"description":"","url":""},
    "paths": {},
    "openapi": "3.1.0",
    "servers": [
        {"description":"DEV Environment","url":"https://my-server-dev.com"},
        {"description":"HML Environment","url":"https://my-server-hml.com"},
        {"description":"PRD Environment","url":"https://my-server.com"}
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Title:            "My Api",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
